# Generated by Django 6.0.3 on 2026-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sensordata_value_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensorstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='watertanklevel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
