# Generated by Django 6.0.1 on 2026-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensordata_sensorstatus_sensordata_watertanklevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='humidity',
            new_name='altitude',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensorstatus',
            field=models.BooleanField(default=False),
        ),
    ]
